from agents.base import BaseAgent, _meta_text
from core.bundle import Bundle


class QualityAgent(BaseAgent):
    VALID_OUTPUTS = ("good", "bad")
    SAFE_DEFAULT = "bad"

    def build_prompt(self, bundle: Bundle) -> str:
        return (
            "You are evaluating a pseudo-label mask generated by SAM for training a "
            "semantic segmentation model. These masks do not need to be perfect — some "
            "boundary imperfection is expected and acceptable.\n\n"
            "You are given three images:\n"
            "  1. RGB camera crop\n"
            "  2. The same crop with the segmentation mask highlighted\n"
            "  3. LiDAR depth projection of the same region\n\n"
            f"{_meta_text(bundle)}\n\n"
            "Mark as GOOD if the highlighted mask roughly covers the correct object region, "
            "even if edges are not perfectly tight.\n\n"
            "Mark as BAD only if the mask is fundamentally wrong: it covers empty road, "
            "sky, or background with no real object present, or it clearly belongs to a "
            "completely different object than the stated class.\n\n"
            "Reply with exactly one word: GOOD or BAD"
        )
