from agents.base import BaseAgent, _meta_text
from core.bundle import Bundle


class QualityAgent(BaseAgent):
    VALID_OUTPUTS = ("good", "bad")
    # Benefit of the doubt: bbox and consistency already catch non-objects.
    # Quality=bad should only fire on clear blobs, not uncertain small objects.
    SAFE_DEFAULT = "good"

    def build_prompt(self, bundle: Bundle) -> str:
        cls = bundle.metadata["class_name"]
        return (
            "You are evaluating a pseudo-label mask generated by SAM for training a "
            "semantic segmentation model. These masks do not need to be perfect — some "
            "boundary imperfection is expected and acceptable.\n\n"
            "You are given three images:\n"
            "  1. RGB camera crop\n"
            "  2. The same crop with the segmentation mask highlighted\n"
            "  3. LiDAR depth projection of the same region\n\n"
            f"{_meta_text(bundle)}\n\n"
            f"Mark as GOOD if there is any object visible under the mask that could "
            f"plausibly be a {cls} — even if small, distant, partially occluded, or "
            "low-resolution. Err on the side of GOOD when uncertain about small objects.\n\n"
            f"Mark as BAD if the mask covers background rather than a {cls}: "
            "vegetation (trees, bushes, shrubs, hedges), grass, road surface, open sky, "
            "a building wall, or a shapeless blob with no distinct object outline.\n\n"
            "Reply with exactly one word: GOOD or BAD"
        )
