from agents.base import BaseAgent, _meta_text
from core.bundle import Bundle


class QualityAgent(BaseAgent):
    VALID_OUTPUTS = ("good", "bad")
    SAFE_DEFAULT = "bad"

    def build_prompt(self, bundle: Bundle) -> str:
        cls = bundle.metadata["class_name"]
        return (
            "You are evaluating a pseudo-label mask generated by SAM for training a "
            "semantic segmentation model. These masks do not need to be perfect — some "
            "boundary imperfection is expected and acceptable.\n\n"
            "You are given three images:\n"
            "  1. RGB camera crop\n"
            "  2. The same crop with the segmentation mask highlighted\n"
            "  3. LiDAR depth projection of the same region\n\n"
            f"{_meta_text(bundle)}\n\n"
            f"Mark as GOOD if the highlighted mask covers a recognizable {cls} and "
            "roughly follows its outline, even if edges are not perfectly tight.\n\n"
            f"Mark as BAD if no {cls} is recognizable under the mask, or the mask "
            "mostly covers something else (trees, bushes, grass, snow, buildings, "
            "road surface, or featureless texture), or it is a shapeless blob that "
            "follows no object outline.\n\n"
            "Reply with exactly one word: GOOD or BAD"
        )
